# -*- coding: utf-8 -*-
"""Initial demoipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tcJhLl--UxOn2huqltbRrI4508MGlT9S
"""

import gensim

from nltk.tokenize import sent_tokenize

corpus = "So I'm a young first gen college graduate, my dad joined the military as soon as he could and my mom dropped out at 16. I never really understood how different I was until I started hanging out with people in the same major as me (Marine Science). I always felt like I missed a crucial stage growing up where my interests would've been nurtured. Most of my studies I just did independently. I hated my teachers in high school because they only seemed to provide their helping hands to the kids who needed it least. I grew a bit of an unhealthy resentment to the preppy kids in my angst-ridden phase. I never really thought of going to college, it wasn't talked about, even with my other siblings. I just kind of wound up there and more or less, ended up winging it. Fast forward a few years and I am succeeding as best I can in classes and still feel like I'm missing something despite usually being near the top of most of my classes, doing climate change research as an undergraduate, leading study sessions with people in the honors college at my university and having many intelligent and motivating friends winning prestigious scholarships. I always felt like I got the concepts of the classes but everybody else seemed to understand the networking and scholarship and opportunity aspects of college. I graduated from a big school with my degree, my peers thought very highly of me, but I always felt less than everyone else. I felt like everyone else had a plan, knew what they were doing. So fast forward some more and here I am. I finally got my first good job in my field and I never really felt more out of place than here. I want to fit in, everybody is so nice, professional and scholarly. All I know how to do is memorize information and regurgitate it on a test and somehow do well. It just feels weird. Maybe it's a confidence thing? I know I can do whatever is needed to be done, I just don't know if I have any thing new to offer or worthwhile to contribute."

import nltk

nltk.download('punkt')

list_of_sentences = sent_tokenize(corpus)

list_of_sentences

list_of_sentences_data = []
for i in list_of_sentences:
  list_of_sentences_data.append(gensim.utils.simple_preprocess(i, deacc= True, min_len = 3))

texts = list_of_sentences_data

texts

bigram = gensim.models.Phrases(list_of_sentences_data)

bigram

from gensim.utils import lemmatize
from nltk.corpus import stopwords

stops = set(stopwords.words("english"))

def process_texts(texts): 
   texts = [[word for word in line if word not in stops] for line in texts] 
   texts = [bigram[line] for line in texts]
   texts = [[word.decode("utf-8").split('/')[0] for word in lemmatize(' '.join(line), allowed_tags=re.compile('(NN)'), min_length=5)] for line in texts]
   #trigrams_ = [t for t in trigram[bigram[sent]] if t.count(' ') == 2]
   return texts

import re

train_texts = process_texts(list_of_sentences_data)
train_texts

from gensim.models import LdaModel
from gensim.models.wrappers import LdaMallet 
from gensim.corpora import Dictionary

train_texts

dictionary = Dictionary(train_texts)
corpus = [dictionary.doc2bow(text) for text in train_texts]

print(dictionary)

print(corpus)

ldamodel = LdaModel(corpus=corpus, num_topics=10, id2word=dictionary)

ldamodel.show_topics()

pip install pyLDAvis

import pyLDAvis
import pyLDAvis.gensim_models

pyLDAvis.enable_notebook()
vis = pyLDAvis.gensim_models.prepare(ldamodel, corpus, dictionary)
vis